### ISSUE TITLE
gfortran compile example in the install instructions does not seem to be enough

### ISSUE THREAD

**Issue by bast** [geospace-code/h5fortran#11]
I tried "if not using CMake FetchContent as is suggested" under https://github.com/geospace-code/h5fortran/blob/master/Install.md#optional-install and this seems to be lacking libraries.

Later I found this: "On Ubuntu it looks like" https://github.com/geospace-code/h5fortran/tree/master/Examples#non-cmake-build which looks more complete. It seems that the two examples do not match.

(working on https://github.com/openjournals/joss-reviews/issues/2842)

**Comment by scivision** [comment]
Yes thank you. I removed the inconsistencies and deduplicated text: https://github.com/geospace-code/h5fortran/blob/main/Install.md#use-h5fortran-from-your-project

The new h5fortran packaging method automatically seeks HDF5 library, the user doesn't need to manually specify that in their own project's CMakeLists.txt

**Comment by bast** [comment]
Thank you for resolving this.
