### ISSUE TITLE
Make Community/Contributing guidelines prominent

### ISSUE THREAD

**Issue by milancurcic** [geospace-code/h5fortran#16]
Currently they're hidden under .github. I almost thought there weren't any until I found them when writing a new issue. It'd be great to have them prominently available in the top-level directory and linked from the README.

openjournals/joss-reviews#2842

**Comment by scivision** [comment]
Thanks I made a link. I use organization-wide templates due to the large number of repositories I have. https://github.com/geospace-code/h5fortran/commit/a8b556260705bad89386bae20e9504c82f42f26d

**Comment by milancurcic** [comment]
Thanks!
