### ISSUE TITLE
Build instructions with CMake not working

### ISSUE THREAD

**Issue by milancurcic** [geospace-code/h5fortran#20]
From README.md:

> cmake --preset=ninja
> cmake --build build

Here's what I get:

```
$ cmake --preset=ninja
CMake Error: The source directory "/home/milan/Work/fortran/h5fortran/--preset=ninja" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

and

```
$ cmake --build build
Error: /home/milan/Work/fortran/h5fortran/build is not a directory
```

Should this rather be `cmake -B build`, which works for me?

My CMake is 3.18.4.

(working on openjournals/joss-reviews#2842)

**Comment by scivision** [comment]
I updated the docs--presets assume CMake >= 3.19. So the docs now work with Cmake < 3.19 as well

**Comment by milancurcic** [comment]
Thanks! Should [this section](https://github.com/geospace-code/h5fortran/blob/main/Install.md#cmake) be updated as well? At least with a note that --preset needs CMake >= 3.19.

**Comment by scivision** [comment]
Thanks I updated that too
