### ISSUE TITLE
Building h5fortran with fpm

### ISSUE THREAD

**Issue by milancurcic** [geospace-code/h5fortran#27]
I'd like to use h5fortran in neural-fortran to allow reading Keras models saved in h5, and writing models trained in neural-fortran. So, I tried this today and found a few modifications that are needed to make this work, at least with the current fpm release (0.5.0):

1. Remove src/read/reader_nd.f90 and src/write/writer_nd.f90. Otherwise, fpm attempts to build them but the module procedures they define don't have a matching interface in the upstream module.
2. Replace the template pre-processing with the corresponding include files and `include` statements:
  a) Rename `*template*.f90` -> `*template*.inc`; otherwise fpm attempts to build the template file alone because of the .f90 suffix
  b) Replace all instances of `@*template*@` in source files with a corresponding `include "*template*.inc"`.
  An advantage of using `include` over @macros@ is that they're standard-conforming and remove the need for a pre-processor.
3. Add the following to fpm.toml:
   ```toml
    [build]
    external-modules = ["hdf5", "h5lt"]
    link = ["hdf5", "hdf5_hl", "hdf5_fortran", "hdf5hl_fortran"]
   ```

If you're open to the above-proposed changes, I'd be happy to prepare a PR. However, I'd need help with making the changes work with CMake and Meson, as I'm not familiar with them. I assume that the changes needed there would be to remove pre-processor instructions.

**Comment by scivision** [comment]
2b: oh yes, that is so much better than needlessly generating source code that's just copying.

Yes I long wanted FPM to work at least with core features, no need to build C/C++ example etc. It looks like FPM could be ready to work with these adjustments

**Comment by scivision** [comment]
I made these changes. Now FPM doesn't find HDF5, there must be some parameter or environment variable for external libraries in arbitrary filesystem locations?

**Comment by scivision** [comment]
Yes this works, fpm 0.5.0 creates libh5fortran.a and h5fortran.mod

**Comment by scivision** [comment]
@milancurcic please let me know if anything else needed, and I'll make a Github release/tag

**Comment by scivision** [comment]
I think I have a few other package (especially nc4fortran which is highly similar to h5fortran, but for NetCDF4) that can use FPM now. At least the ones that don't use C/C++.
E.g. fortran-filesystem is a killer app for me but it entirely relies on C++ source code mixed with .f90 internal to the library.

**Comment by scivision** [comment]
[nc4fortran](https://github.com/geospace-code/nc4fortran) now also works with FPM

**Comment by milancurcic** [comment]
It works on my end, please go ahead with the release.

**Comment by scivision** [comment]
@milancurcic [h5fortran-mpi](https://github.com/geospace-code/h5fortran-mpi) now also has FPM build
