### ISSUE TITLE
How do I read string array?

### ISSUE THREAD

**Issue by gekowa** [geospace-code/h5fortran#33]
README says: "Polymorphic [API](https://github.com/geospace-code/h5fortran/blob/main/API.md) with read/write types int32, int64, real32, real64 with rank scalar (0-D) through 7-D **as well as character (string)**.".

But when I read string array from HDF5, it still throws "ERROR:h5fortran:reader: character arrays (non-singleton) not yet supported by h5fortran.".

Anything I've missed? Please help, thanks a lot.

**Comment by scivision** [comment]
Thank you, I corrected the Readme in e116732.

I would need to make an enhancement to the code to read string arrays. 

Are you interested in 1-D vectors of character arrays, read/write, ... ?

**Comment by gekowa** [comment]
Thanks for your response. 👍 

Yes, I am interested in 1-D vectors of character arrays, and to be frankly, I also need 0-D to 3-D character arrays. 😉 

I don't mean to hurry you, but my project is now choosing a library for HDF5 handling, I need to know approximately when the character array feature is ready, in order to decide if I need to wait or come back later.

Thanks again.

**Comment by scivision** [comment]
I have a prototype that works for reading fixed length character arrays. I believe I found a method to read variable length character arrays as well. I am crunched for time myself, but I think in next several days it can be ready.

**Comment by gekowa** [comment]
Awesome! I think fixed length character array would be enough for me. Looking forward to your work!

**Comment by scivision** [comment]
This was implemented in 12e801a. Thanks!

**Comment by gekowa** [comment]
Hooray! 
Thank you so much, you make my day!
