### ISSUE TITLE
Write Attribute: Is it possible?

### ISSUE THREAD

**Issue by nyckmaia** [geospace-code/h5fortran#5]
Is there a way to write a HDF5 attribute?

**How can I do that?**

**Comment by scivision** [comment]
Thanks I realized this was not documented though it was been a feature for a long time.

```fortran
call h5f%initialize('test_attr.h5')

call h5f%write('/x', 1)

call h5f%writeattr('/x', 'note', 'this is just a little number')

call h5f%writeattr('/x', 'hello', 'hi')

call h5f%finalize()
```

**Comment by scivision** [comment]
h5fortran v2.11.0 has full read / write attribute support. thank you.
