### ISSUE TITLE
LNK2019: unresolved external symbol, H5FORTRAN_mp_LT1WRITE

### ISSUE THREAD

**Issue by nyckmaia** [geospace-code/h5fortran#6]
I wrote a simple Fortran static library using thi single `*.f90` file:

```
module mod
    
    use h5fortran
    use ISO_C_BINDING
    
    contains
    subroutine xxx() bind(C, name = 'f_x')
        call h5write('golt.h5','/x', [1,2,3,4,5,6])
    end subroutine xxx
end module mod
```
After that, I call the `f_x` subroutine in my C++ application:

```
extern "C" {
    void f_x(void);
}

int main()
{
    f_x();

    return 0;
}
```
Library Directory: `C:\HDF5\1.12.0\lib`
Include Directory: `C:\HDF5\1.12.0\include`

Linked HDF5 libraries:
- hdf5.lib
- hdf5_fortran.lib 
- hdf5_cpp.lib 
- hdf5_f90cstub.lib 
- hdf5_hl.lib 
- hdf5_hl_cpp.lib 
- hdf5_hl_fortran.lib 
- hdf5_hl_f90cstub.lib 
- hdf5_tools.lib 
- szip.lib 
And `lib` prefix versions:
- libhdf5.lib 
...
- libhdf5_tools.lib

Of course, I linked my own generated Fortran static library `Lib1.lib` and a single Fortran library dependence called `ifmodintr.lib`

But I got this **compile time error below:**
```
LNK2019: unresolved external symbol, H5FORTRAN_mp_LT1WRITE
```

Could you help me?

**How can I fix it?**

My system:
- WIndows 10 x64
- Intel Fortran 19 (Microsoft Visual Studio Community 2019)
- MSVC 2019
- HDF5 1.12.0

**Comment by nyckmaia** [comment]
Sorry about that...
I forgot to link the `h5fortran.lib`...

**Now it works great!**

**Comment by scivision** [comment]
I think Intel Fortran on Windows is the trickiest linking situation for HDF5, but one that does work as you see. I also regularly using HDF5 + h5fortran with Intel compiler or GCC on Windows.

In general, the easiest way to use h5fortran cross platform is to use CMake. Then if your program above is named "main.f90" the CMakeLists.txt for your project is like

```cmake
cmake_minimum_required(VERSION 3.14)
project(MyTest Fortran)

include(FetchContent)

FetchContent_Declare(h5fortran_proj
  GIT_REPOSITORY https://github.com/geospace-code/h5fortran.git
  GIT_TAG master  # whatever desired version is
)

FetchContent_MakeAvailable(h5fortran_proj)

# ------------------------------------------------------
add_executable(my_program main.f90)
target_link_libraries(my_program h5fortran::h5fortran)
```

**Comment by scivision** [comment]
This question has come up a few times, I think I will make a simple standalone example for this under Examples/

**Comment by scivision** [comment]
https://github.com/geospace-code/h5fortran/tree/master/Examples
